FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# rails-twitter

Polls is a simple API allowing consumers to view polls and vote in them.

# group Tweet            

## Tweets Collection [/tweets]

### List all Tweets [GET]

+ Response 200 (application/json)

        [
            {
                "text": "Hello World",
                "created_at": "2017-06-05T08:40:51.620Z",
            },
            {
                "text": "Bye World",
                "created_at": "2017-06-20T08:40:51.620Z",
            }
        ]


## Show Tweet [/tweets/{id}]

+ Parameters

    + id: 1001 (number, required) - Id of a tweet.

### Show Tweet [GET]

+ Response 200 (application/json)
                
    + Body

            {
                "text": "Hello World",
                "created_at": "2017-06-05T08:40:51.620Z",
            }